<a href="https://colab.research.google.com/github/0bsidian03/CompPhysQuizz/blob/main/Linalgquiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import required packages
import numpy as np

In [ ]:
M = np.array([[1.0,  -4.0, -0.5, -2.5,  2.0],
              [-4.0,  3.0, -5.5, -5.5, -3.5],
              [-0.5, -5.5,  7.0, -2.0,  3.5],
              [-2.5, -5.5, -2.0, -2.0, -4.0],
              [ 2.0, -3.5, -3.5, -4.0,  1.0]])

b = np.array([1, -1, 2, -1, 0])

In [ ]:
for i in range(M.shape[0]):
    terms = []
    for j in range(M.shape[1]):
        terms.append("{1} x[{0}]".format(j, M[i, j]))
    print(" + ".join(terms), "=", b[i])

1.0 x[0] + -4.0 x[1] + -0.5 x[2] + -2.5 x[3] + 2.0 x[4] = 1
-4.0 x[0] + 3.0 x[1] + -5.5 x[2] + -5.5 x[3] + -3.5 x[4] = -1
-0.5 x[0] + -5.5 x[1] + 7.0 x[2] + -2.0 x[3] + 3.5 x[4] = 2
-2.5 x[0] + -5.5 x[1] + -2.0 x[2] + -2.0 x[3] + -4.0 x[4] = -1
2.0 x[0] + -3.5 x[1] + -3.5 x[2] + -4.0 x[3] + 1.0 x[4] = 0


In [ ]:
def qrdecomp(M):
  n=M.shape[0]
  M_working=np.copy(M)
  Q=np.zeros((n,n))
  R=np.zeros((n,n))
  for i in range(n):
    for j in range(i):
      R[j,i]=np.sum(Q[:,j]*M[:,i])
      M_working[:,i]-=R[j,i]*Q[:,j]
  R[i,i]=np.sqrt(np.sum(M_working[:,i]*M_working[:,i]))
  Q[:,i]=M_working[:,i]/R[i,i]

  return Q,R


print("Matrix Q:")
print(Q)
print("\nMatrix R:")
print(R)

Matrix Q:
[[-0.19069252 -0.38369783  0.2353589   0.19143061 -0.85110096]
 [ 0.76277007  0.20945823  0.2937686   0.53280431 -0.06425455]
 [ 0.09534626 -0.57276632 -0.64791879  0.46549041  0.16238148]
 [ 0.47673129 -0.62096025  0.24565574 -0.55994303  0.11512035]
 [-0.38138504 -0.30862651  0.61494772  0.38633712  0.48153719]]

Matrix R:
[[-5.24404424  1.23950137 -3.05108029 -3.33711906 -5.00567859]
 [ 0.          9.808855   -2.64742234  3.42918349 -1.32996711]
 [ 0.          0.         -8.91246678 -3.85938929 -3.1928633 ]
 [ 0.          0.          0.         -4.76544345  2.77337183]
 [ 0.          0.          0.          0.         -0.88792002]]


In [ ]:
Q,R=  np.linalg.qr(M) #run as doubvle check

print("Matrix Q:")
print(Q)
print("\nMatrix R:")
print(R)

Matrix Q:
[[-0.19069252 -0.38369783  0.2353589   0.19143061 -0.85110096]
 [ 0.76277007  0.20945823  0.2937686   0.53280431 -0.06425455]
 [ 0.09534626 -0.57276632 -0.64791879  0.46549041  0.16238148]
 [ 0.47673129 -0.62096025  0.24565574 -0.55994303  0.11512035]
 [-0.38138504 -0.30862651  0.61494772  0.38633712  0.48153719]]

Matrix R:
[[-5.24404424  1.23950137 -3.05108029 -3.33711906 -5.00567859]
 [ 0.          9.808855   -2.64742234  3.42918349 -1.32996711]
 [ 0.          0.         -8.91246678 -3.85938929 -3.1928633 ]
 [ 0.          0.          0.         -4.76544345  2.77337183]
 [ 0.          0.          0.          0.         -0.88792002]]


In [ ]:
print("Result of Q^T * Q: ")
print(Q.T @ Q)

Result of Q^T * Q: 
[[ 1.00000000e+00 -8.46830792e-17  1.43452291e-16  9.98007721e-17
  -4.19151227e-16]
 [-8.46830792e-17  1.00000000e+00 -1.21020566e-16 -9.63725583e-17
   6.22899576e-17]
 [ 1.43452291e-16 -1.21020566e-16  1.00000000e+00  2.66514643e-17
  -1.96791719e-16]
 [ 9.98007721e-17 -9.63725583e-17  2.66514643e-17  1.00000000e+00
  -4.62209885e-17]
 [-4.19151227e-16  6.22899576e-17 -1.96791719e-16 -4.62209885e-17
   1.00000000e+00]]


In [ ]:
y = Q.T@b

x =  np.linalg.inv(R) @ y

print("The solution to the provided system of equations is: ", x)

The solution to the provided system of equations is:  [-0.43042175 -0.104166   -0.11273641  0.13709444  0.65006283]


In [ ]:
x_M = np.linalg.solve(M, b)

print("The solution to the provided system of equations is: ", x_M)

The solution to the provided system of equations is:  [-0.43042175 -0.104166   -0.11273641  0.13709444  0.65006283]


In [ ]:
A = np.array([[16, 10, 7],
              [10, -8, 0],
              [7, 0, 6]])

In [ ]:
def qr_eigen (input,itmax=100):
  A_copy=np.copy(A)
  for iteration in range(1,itmax):
    Q,R=qrdecomp(A_copy)
    A_copy=np.dot(R,Q)

  eigvalues=np.diag(A_copy)
  eigvectors=np.linalg.inv(Q)
  return eigvalues,eigvectors


print(f"\nEigenvalues: {eigvalues}")
print(f"Eigenvectors:\n{eigvectors}")


Eigenvalues: [ 22.30499895 -11.96276574   3.65776679]
Eigenvectors:
[[-0.8793615  -0.36466577 -0.30617353]
 [-0.29017044  0.92023045 -0.2626348 ]
 [-0.37752413  0.14210843  0.91503045]]


In [ ]:
eigvalues, eigvectors = np.linalg.eig(A)#check against np

print(f"\nEigenvalues: {eigvalues}")
print(f"Eigenvectors:\n{eigvectors}")


Eigenvalues: [ 22.30499895 -11.96276574   3.65776679]
Eigenvectors:
[[-0.8793615  -0.36466577 -0.30617353]
 [-0.29017044  0.92023045 -0.2626348 ]
 [-0.37752413  0.14210843  0.91503045]]


In [ ]:
D = np.diag(eigvalues)

P = eigvectors

print("Matrix D:")
print(D)

print("\nMatrix P:")
print(P)

Matrix D:
[[ 22.30499895   0.           0.        ]
 [  0.         -11.96276574   0.        ]
 [  0.           0.           3.65776679]]

Matrix P:
[[-0.8793615  -0.36466577 -0.30617353]
 [-0.29017044  0.92023045 -0.2626348 ]
 [-0.37752413  0.14210843  0.91503045]]


In [ ]:
P_inverse = np.linalg.inv(P)

print("Matrix P-inverse:")
print(P_inverse)

Matrix P-inverse:
[[-0.8793615  -0.29017044 -0.37752413]
 [-0.36466577  0.92023045  0.14210843]
 [-0.30617353 -0.2626348   0.91503045]]


In [ ]:
print("Original Matrix A:")
print(A)

print("\nResult of PDP^-1:")
print((P@D@P_inverse))

Original Matrix A:
[[16 10  7]
 [10 -8  0]
 [ 7  0  6]]

Result of PDP^-1:
[[ 1.60000000e+01  1.00000000e+01  7.00000000e+00]
 [ 1.00000000e+01 -8.00000000e+00  1.94968510e-15]
 [ 7.00000000e+00  5.30722969e-15  6.00000000e+00]]
